#!/bin/bash
# start.sh — launches פיננסיקס locally via `serve`, no build step required.
set -e

PORT=3000
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IP="$(ipconfig getifaddr en0 2>/dev/null || true)"
if [ -z "$IP" ]; then
  IP="$(ipconfig getifaddr en1 2>/dev/null || true)"
fi

# FINEDU_UNLOCK_ALL=1 ./start.sh shows every world unlocked on the map,
# regardless of quiz progress — a dev/testing convenience, not a kid-facing
# setting. There's no real server here to read env vars at request time, so
# we bake the flag into a static file the browser JS imports directly,
# rewritten on every launch to match this run's environment.
if [ -n "$FINEDU_UNLOCK_ALL" ]; then
  UNLOCK_VALUE="true"
else
  UNLOCK_VALUE="false"
fi
cat > "$DIR/public/debug-flags.js" <<EOF
// debug-flags.js — regenerated by start.sh on every launch based on the
// FINEDU_UNLOCK_ALL environment variable. Not meant to be hand-edited.
export const UNLOCK_ALL_WORLDS = $UNLOCK_VALUE;
EOF

echo "מפעיל את פיננסיקס..."
echo ""
if [ -n "$FINEDU_UNLOCK_ALL" ]; then
  echo "⚠️  FINEDU_UNLOCK_ALL מופעל — כל העולמות יוצגו פתוחים במפה."
  echo ""
fi
if [ -n "$IP" ]; then
  echo "כתובת ברשת המקומית (למכשירים נוספים): http://$IP:$PORT"
else
  echo "לא נמצאה כתובת רשת מקומית (Wi-Fi) — האפליקציה תהיה זמינה רק במחשב זה"
fi
echo "כתובת במחשב הזה: http://localhost:$PORT"
echo ""

npx serve "$DIR/public" -l "$PORT"
